### PR TITLE
Massive changes - New project direction

### PR DESCRIPTION
**Pull request by Choroid**
Lots of changes  - I've updated it to Python3, converted to Postgres, removed points, and much much more

### CODE REVIEW

**Comment by Choroid** [comment]
I've started a new repo jumping off of this point. https://github.com/clemsonMakerspace/Magstripe_Attendance

**Comment by shanet** [comment]
Hi Owen,

As you've noticed, I originally wrote this years ago for the ACM chapter at my university. I've since graduated and am no longer affiliated with the club so I don't maintain it anymore.

I'm glad to see that you've found it useful however and have forked it for your own purposes. If you plan to continue maintaining it, I'd be happy to put a link to your fork in the README. Let me know if that's okay.

The one issue I have with this, though, is that you changed the license from the LGPL to the GPL. As the original author and copyright holder, only I can authorize that the license be changed. Of course, you are free to choose any LGPL-compatible license you wish for your changes, but I request that the original project remain licensed under the LGPL with its license intact. Thank you for your understanding.

Side note (just for your reference): GNU recommends having the license in a file called `COPYING` instead of `LICENSE.txt`. https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by shanet** [comment]
Another thing you might want to look into is moving from PyQt to PySide. The licensing and documentation are better. It's a drop-in in replacement so switching from one to the other is a relatively painless process.

**Comment by Choroid** [comment]
Hey Shane!

I'd like to apologize for the licensing issue. I was under the impression that in creating a derivative work I was allowed to transition from LGPLv3 to GPLv3 - I'll convert back in my next commit. I hope that all of the other copyright notices are acceptable for you!

I would appreciate a shout-out in your README - I plan on using this project for the next four years at least. 

I'll also start looking into PySide - Thanks for the heads-up!

**Comment by shanet** [comment]
No worries, thanks for changing the license. You entirely entitled to use the GPL for your modifications if you like. Also I added a note to the README with a link to your fork. Thanks for letting me know about your changes!

**Pull request closed without merging**
